### ISSUE TITLE
Improve error handling in `upgrade`?

### ISSUE THREAD

**Issue by LukasKalbertodt** [de-vri-es/hyper-tungstenite-rs#1]
Hi there and thanks for the library!

I wanted to check what errors can be returned from `upgrade` and saw this:

https://github.com/de-vri-es/hyper-tungstenite-rs/blob/48b6b56963e7556023fb3f37700fb3c87dc80d9a/src/lib.rs#L98-L103

I think the code shouldn't use `?` at the end. As far as I understand the response builder of hyper, the `body` only returns a `Result` if the builder was used incorrectly, i.e. specifying bad header values. See [the docs](https://docs.rs/http/0.2.3/http/response/struct.Builder.html#method.body):

> This function may return an error if any previously configured argument failed to parse or get converted to the internal representation. For example if an invalid `head` was specified via `header("Foo", "Bar\r\n")` the error will be returned when this function is called rather than when `header` was called.

So I think an `unwrap` or `expect` is actually more appropriate in this code as an error there would indicate a *bug* in the function. And for bugs, panics are used; `Err(_)` is only for recoverable errors. 

In that case, the function could also just return a [`ProtocolError`](https://docs.rs/tungstenite/0.13.0/tungstenite/error/enum.ProtocolError.html) instead? Being more specific here would be nice from a perspective of a user of this library. 

Ultimately, I want to decide: what to do in case of an error? I have to respond *something*. Well, I could just send nothing, but that's also not great. So if I'm understanding `update` correctly, an `Err(_)` would indicate a client error. Meaning I should respond with some 4xx code.

I can send a PR if you agree with this reasoning.

**Comment by de-vri-es** [comment]
Hey, thanks for your suggestion.

It makes sense and I definitely agree. A PR would be great :)

/edit: it looks like we're still stuck with `tungstenite` 0.12 because of `tungstenite-tokio`. That means the protocol error is still just a `Cow<'static, str>`. To take full advantage of the new 0.13 error types, we could also switch to `async-tungstenite` instead of `tokio-tungstenite`. Otherwise we should wait for `tokio-tungstenite` to update to `tungstenite` 0.13, since  there is no gain for the user if we stick with `tungstenite` 0.12.

**Comment by de-vri-es** [comment]
I submitted https://github.com/snapview/tokio-tungstenite/pull/157 to try and get `tungstenite-tokio` to upgrade :)

**Comment by LukasKalbertodt** [comment]
Thanks for the quick reply and the investigation. I don't have an opinion on `async-tungstenite` vs `tokio-tungstenite` as I'm using Tokio. I am totally fine with waiting!

**Comment by de-vri-es** [comment]
> Thanks for the quick reply and the investigation. I don't have an opinion on `async-tungstenite` vs `tokio-tungstenite` as I'm using Tokio. I am totally fine with waiting!

Yeah, `hyper` already forces you to use `tokio`, so I figured using `tokio-tungstenite` made more sense. I'm still leaning that way, so let's see what happens with snapview/tokio-tungstenite#157 then. If it takes too long or gets rejected, we can still switch to `async-tungstenite`.

**Comment by LukasKalbertodt** [comment]
> `hyper` already forces you to use `tokio`,

Oops, right, forgot that. In that case, `tokio-tungstenite` makes perfect sense.

**Comment by de-vri-es** [comment]
They merged https://github.com/snapview/tokio-tungstenite/pull/147, so now it's just waiting for a release :)

**Comment by de-vri-es** [comment]
And now it's also released. So I would welcome a PR to implement your suggestion :)

**Comment by LukasKalbertodt** [comment]
Great! Working on it.

EDIT: nevermind, I'm pretty sure it's `ProtocolError::HandshakeIncomplete`.

~~Quick question: in the following code:~~

https://github.com/de-vri-es/hyper-tungstenite-rs/blob/48b6b56963e7556023fb3f37700fb3c87dc80d9a/src/lib.rs#L182

I'm having trouble finding a fitting `tungstenite::error::Error` for that case. It is not a `ProtocolError`, I think? Do you know what error would fit here?

**Comment by de-vri-es** [comment]
> EDIT: nevermind, I'm pretty sure it's `ProtocolError::HandshakeIncomplete`.

TBH I don't know how the upgrade can fail. To my knowledge, the upgrade is complete once the response is sent. The only thing I can think of is that the client closed the connection. So `HandshakeIncomplete` sounds like the right choice :)
