### ISSUE TITLE
how to use tokio::io::split to split WebSocketStream to read/write part

### ISSUE THREAD

**Issue by pymongo** [de-vri-es/hyper-tungstenite-rs#10]
![image](https://user-images.githubusercontent.com/42347370/164446263-0b2c5e3c-8895-4b77-81d9-e24ce7ab2bdc.png)

**Comment by pymongo** [comment]
tokio_tungstenite can split ws_stream to read/write

how to split hyper-tungstenite stream to read/write

**Comment by de-vri-es** [comment]
You end up with a `tokio_tungestenite::WebSocketStream`, so you should be able to do exactly the same :)

**Comment by de-vri-es** [comment]
But I'm not sure you are correct: `tokio::io::split` seems to require `AsyncRead + AsyncWrite`. `tokio_tungstenite::WebSocketStream` implements neither: https://docs.rs/tokio-tungstenite/latest/tokio_tungstenite/struct.WebSocketStream.html#trait-implementations

**Comment by pymongo** [comment]
> You end up with a `tokio_tungestenite::WebSocketStream`, so you should be able to do exactly the same :)

the inner of WebsocketStream is hyper::Upgraed which impl tokio async read/write trait

I can split by WebSocketStream::get_mut();

here is a example in hyper-websocket split

```rust
async fn handle_ws(ctx: AppContext, websocket: HyperWebsocket) -> Result<(), Error> {
    let mut ws_stream = websocket.await?;
    let (rx, tx) = tokio::io::split(ws_stream.get_mut());
```

and compare to tokio-tungestenite `ws_stream.split()`

```rust
async fn accept_connection(stream: TcpStream) {
    let addr = stream.peer_addr().expect("connected streams should have a peer address");
    let ws_stream = tokio_tungstenite::accept_async(stream)
        .await
        .expect("Error during the websocket handshake occurred");
    let (write, read) = ws_stream.split();
```

**Comment by de-vri-es** [comment]
Right, but you shouldn't be using the inner stream. Websockets have their own framing mechanism. If you use the inner stream you're sending/receiving raw bytes, and you'll have to do the work done by `tokio-tungstenite` yourself.

But why doesn't `ws_stream.split()` work for `WebSocketStreams` created by this crate?

**Comment by de-vri-es** [comment]
`stream.split()` works out of the box. I've added a test case to confirm it:
https://github.com/de-vri-es/hyper-tungstenite-rs/blob/cb704cf003b4e4def621b05ed6b5dc433c709577/tests/split.rs#L46-L50
