### ISSUE TITLE
send message to all connected users

### ISSUE THREAD

**Issue by johansmitsnl** [de-vri-es/hyper-tungstenite-rs#17]
I have a separate thread that retrieves data. When this data is updated I want to relay this to all connected users. What is the correct way of storing the connected connections and send the message to them?

**Comment by de-vri-es** [comment]
Hey, thanks for your interest. However, you question is more of a general Rust programming question than an issue with this crate. As much as I would like to help you, I do not have the time for general programming questions.

Be sure to read the Rust book for useful information on this topic. In particular, check out [chapter 16](https://doc.rust-lang.org/stable/book/ch16-00-concurrency.html) for information about concurrency. In particular, sections 16.2 and 16.3 should help you with this problem.

Good luck!
