### ISSUE TITLE
Can not use tokio-tracing #[instrument] macro with functions having HyperWebsocket as a parameter.

### ISSUE THREAD

**Issue by DanielJoyce** [de-vri-es/hyper-tungstenite-rs#4]
Says that HyperWebsocket doesn't implement Debug.

Would be nice to add it so it works with the tracing library easily.

**Comment by de-vri-es** [comment]
Thanks for the suggestion. I've added `#[derive(Debug)]` to the struct and released it as 0.3.2 :)

**Comment by DanielJoyce** [comment]
Awesome. Thanks!
