### ISSUE TITLE
Example should not use Box<dyn Error>

### ISSUE THREAD

**Issue by Darksonn** [de-vri-es/hyper-tungstenite-rs#7]
It's generally best to use `Box<dyn Error + Send + Sync>` instead when it comes to async examples as otherwise you can get errors regarding `Send`.

**Comment by de-vri-es** [comment]
Good point. I've updated the example to a full server application. That should make sure that this can't go wrong again in the future :)

Thanks for reporting this! It's released as 0.4.1.
