### ISSUE TITLE
WebSocketConfig is used in the public API but not reexported

### ISSUE THREAD

**Issue by mgattozzi** [de-vri-es/hyper-tungstenite-rs#8]
Hello! I'm prefacing this by saying I don't need this, I just wanted to bring it to your attention. If you look [here on line 127](
https://github.com/de-vri-es/hyper-tungstenite-rs/blob/ee85814c7d17e9a70757495b67dc7f22db20eea6/src/lib.rs#L127) we see that there is a `WebSocketConfig` type in the public API. However, this is not reexported like some other types as seen [here](https://github.com/de-vri-es/hyper-tungstenite-rs/blob/ee85814c7d17e9a70757495b67dc7f22db20eea6/src/lib.rs#L96-L100). Which leads to these docs [showing a type that can't be used in the upgrade function](https://docs.rs/hyper-tungstenite/0.4.1/hyper_tungstenite/fn.upgrade.html). If one puts `tungstenite = "^0.14.0"` in their Cargo.toml then this type can be used, but tungstenite is currently on "0.15.0" and people might find it confusing when trying to figure it out. The error message when this version mismatch occurs at least somewhat points the way. I'm guessing this was just oversight or something and there is a work around if it's needed, but I wanted to let you know!

**Comment by de-vri-es** [comment]
Interesting. I actually exported the entire `tungstenite` crate as a catch-all, but that link also got broken on docs.rs: https://docs.rs/hyper-tungstenite/0.4.1/hyper_tungstenite/index.html#reexports

Not sure whats going on exactly, but I'll definitely fix this somehow :)

Thanks for reporting this!

**Comment by de-vri-es** [comment]
It seems that re-exporting a re-export doesn't work correctly with `rustdoc`. As a work-around, I added a direct dependency on `tungstenite` and re-export that.

It's released as 0.4.2. I also updated to tungestine 0.16 and released that as 0.5.0.

Thanks again for reporting the issue!
